### ISSUE TITLE
Support JSON serialization for complex properties

### ISSUE THREAD

**Issue by justinspradlin** [AntoineGa/Seq.App.Teams#11]
It would be very useful to have a feature where the user can configure certain properties to serialize as JSON on the output. In my particular use case I want to be able to view complex information about health reports via the Teams message card. 

See PR https://github.com/AntoineGa/Seq.App.Teams/pull/10 for a potential solution.

**Comment by AntoineGa** [comment]
fixed by @justinspradlin in 1.0.22
