### ISSUE TITLE
Make project cross platform

### ISSUE THREAD

**Issue by xantari** [AntoineGa/Seq.App.Teams#14]
Currently Seq provides linux based docker images, this poses a problem for Seq apps that were built against full framework which is not available in the linux based Seq docker container 

https://hub.docker.com/r/datalust/seq

Need to convert this package to .NET Standard 2.0 so that it is available cross platform.

**Comment by AntoineGa** [comment]
i agree

**Comment by xantari** [comment]
FYI, i just migrated https://github.com/xantari/Seq.App.Azure.DevOps to .NET Standard 2.0 to make it cross platform and runnable in a docker linux container.

Let me know if you want to take this on or if you want me to do a PR

**Comment by AntoineGa** [comment]
i won't have time until next year, so if you are interested in it, feel free to do a PR, please !
