### ISSUE TITLE
Could not load file or assembly 'System, Version=4.0.0.0'

### ISSUE THREAD

**Issue by xantari** [AntoineGa/Seq.App.Teams#16]
Version 1.0.0.22 (Latest Version as of this writing) is throwing this error on Seq version 2021.2.5647

System.IO.FileNotFoundException: Could not load file or assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
File name: 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at Seq.App.Teams.TeamsReactor.On(Event`1 evt)
   at SeqCli.Apps.Hosting.AppContainer.SendTypedEventAsync(String clef)

I kinda wonder if this is due to Seq being a .net core application now and the plugin is still full framework only. See #14

**Comment by nblumhardt** [comment]
I'll have a look now :+1:

**Comment by xantari** [comment]
FYI, I removed all the previous versions from c:\programdata\seq and rebooted the server and things are back to normal. Not sure what the exact issue was but seems to be resolved. Though this plugin does need to be updated to be .net standard 2.0 so it works in the seq docker images (#14). I’ll close this issue..

**Comment by nblumhardt** [comment]
:+1:

#17 adds `netstandard2.0` :-)
