### ISSUE TITLE
CI build is not picking up appveyor.yml

### ISSUE THREAD

**Issue by nblumhardt** [AntoineGa/Seq.App.Teams#18]
CI is [currently failing](https://ci.appveyor.com/project/GAYAntoine/seq-app-teams/builds/40991049):

> Build started
> git clone -q --branch=master https://github.com/AntoineGa/Seq.App.Teams.git C:\projects\seq-app-teams
> git checkout -qf 702d01914489d954ceda543f0821b70dfdc26f78
> msbuild "C:\projects\seq-app-teams\Seq.App.Teams.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
> Microsoft (R) Build Engine version 14.0.25420.1
> Copyright (C) Microsoft Corporation. All rights reserved.
> C:\projects\seq-app-teams\Seq.App.Teams\Seq.App.Teams.csproj(1,1): error MSB4041: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.
> Command exited with code 1

You can see that AppVeyor is kicking of MSBuild 14 directly; the build script uses `Build.ps1` to invoke a `dotnet` build, which will show different output.

AppVeyor usually does this when it's in a state that ignores appveyor.yml, either because it's set up as a generic Git repository (rather than the GitHub repository type), or when its permissions are incorrect.

Not sure what the easiest way to tackle this will be, but because the build number maintained by AppVeyor isn't crucial for the build numbering scheme used here, deleting and re-creating the project in the AppVeyor UI is probably the fastest fix.

**Comment by AntoineGa** [comment]
I do not like MsBuild.
I have switched from using MsBuild in AppVeyor to directly use the build script in Powershell, and now it works.

**Comment by nblumhardt** [comment]
Looks good! :+1:
