### ISSUE TITLE
[RFC] Filter by application

### ISSUE THREAD

**Issue by ionutvasiliu** [AntoineGa/Seq.App.Teams#3]
Is there a way that we can send to Teams only the logs of a certain Application?

Let's say we have 2 apps which are writing to the same seq instance: A and B. I would like to configure 2 channels in Teams (channel-A and channel-B) so that all logs from application A are sent to channel-A and all logs from application B are sent to channel-B.

Thanks.

**Comment by AntoineGa** [comment]
Ok, you need to specify only 2 channels or would you rather specify a mapping for an unlimited number of filter / channel ?

**Comment by ionutvasiliu** [comment]
First of all for the feedback.

Second, to answer you question, ideally I would like to specify in my Teams Seq instance a filter so that only those messages will be sent to my Teams channel. From UI perspective I assume that most probably this can be added here
![image](https://user-images.githubusercontent.com/4112662/43117975-480b5d04-8f18-11e8-8bc4-f2921b62740d.png)

**Comment by AntoineGa** [comment]
I don't get it.

You have 1 Seq instance, and want to map 1 filter to 1 Teams channel twice, am i right ?

How will you specify the mapping between Seq Filter and Teams Channel in the UI ?

**Comment by ionutvasiliu** [comment]
I have 3 applications A, B and C. All 3 of them are writing logs to one instance of Seq (let's call it S).

I want to get in Teams all logs from A. How do I have to configure you application to achieve this? Thanks.

**Comment by nblumhardt** [comment]
@ionutvasiliu in Seq, if you create a [signal](https://docs.getseq.net/docs/signals) to identify events from `A`, then you can send only this signal to the app.
