### ISSUE TITLE
Teams Alert text contains text for "System.Collections.Generic.Dictionary`2[System.String,System.Object]"

### ISSUE THREAD

**Issue by dlaudams** [AntoineGa/Seq.App.Teams#32]
Hi,

The Seq.App.Teams plug-in app posts alert messages into Teams with broken text. It looks like the the output of a C# Object.ToString().

Instead I would expect to see the contents of the dictionary.

I'm using Seq.App.Teams 2.0.38, Seq 2021.3.6800, which is running on the Docker container image datalust/seq:2021.3.

Here is an example alert message:

![image](https://user-images.githubusercontent.com/51695764/154612334-18406820-ba28-447d-ba70-85b63da882c4.png)

Thanks,
Daniel.

**Comment by nblumhardt** [comment]
I think this ties in with #30 and #12. I'll pop an item on our to-do list at Datalust and try to loop back to propose some improvements/a PR ASAP 👍

**Comment by TheNr1Guest** [comment]
To fix/workaround this you need to go to your Teams instance configuration within Seq and find the text field that says 'Properties to serialize as JSON (optional)'. Enter the following:

```
Alert
Source
```

From now on you will see the raw JSON for those properties.
