### ISSUE TITLE
Wrong base url on 'Open Seq Alert' button

### ISSUE THREAD

**Issue by sergiojrdotnet** [AntoineGa/Seq.App.Teams#42]
# Instance

![image](https://user-images.githubusercontent.com/72770006/210240578-7d6ab6f7-d09d-419e-80cb-caf6542413fb.png)

# Webhook

![image](https://user-images.githubusercontent.com/72770006/210240695-3e6819d2-d1fc-4d63-a185-d1ce657acb6f.png)

# Versions

Seq 2022.1.7929

![image](https://user-images.githubusercontent.com/72770006/210240814-5c7774f3-46fd-41fd-aed8-27ab82987dc0.png)

**Comment by nblumhardt** [comment]
Hi! I think this setting should be/may already be obsolete - Seq needs to know its base URL for a lot of functionality to work, and it provides this info through to the app.

If you're running in Docker, setting `SEQ_API_CANONICALURI` to the fully-qualified address of your Seq server will fix this.

On Windows,

```
seq config set -k api.listenUri -v "https://something"
seq service restart
```

will do it.

I'll loop back around to this and see if I can figure out what is going on in the app/whether and how the setting can be removed. HTH!

**Comment by sergiojrdotnet** [comment]
It was fixed after changing the `api.listenUris` config, thanks @nblumhardt 
I'll leave this issue open until the obsolete setting be removed.
