### ISSUE TITLE
Updated Nuget publish to nuget.org?

### ISSUE THREAD

**Issue by xantari** [AntoineGa/Seq.App.Teams#7]
This here says updated 8 months ago: https://www.nuget.org/packages/Seq.App.Teams/

However I see on Github there was a change 3 months ago to update password property?

No auto-deploy to nuget occurring?

**Comment by AntoineGa** [comment]
no, i have not got time to do it sadly
each time i publish manually a package i write a note to myself to automate it

**Comment by AntoineGa** [comment]
done thanks to @xantari and #8
